name: Docker Build, Push, and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to private Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.CLOUDFLARE_REGISTRY_URL }}
        username: ${{ secrets.CLOUDFLARE_REGISTRY_USERNAME }}
        password: ${{ secrets.CLOUDFLARE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.CLOUDFLARE_REGISTRY_URL }}/marianobe-site:${{ env.SHA }}
